from __future__ import annotations

import json
import secrets
import zipfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .redaction import redact_text, sanitize_mapping


@dataclass
class HandoffContext:
    project_id: str
    project_name: str
    run_id: str | None
    milestone: str | None
    stage: str
    incident_id: str | None = None
    incident_challenge: str | None = None
    checkpoint: dict[str, Any] = field(default_factory=dict)
    technical: dict[str, Any] = field(default_factory=dict)
    notes: str = ""


class HandoffBuilder:
    VALID_KINDS = {"BOOTSTRAP", "CONTINUITY", "INCIDENT", "AUDIT"}

    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)

    def _context(self, kind: str, context: HandoffContext) -> dict[str, Any]:
        if kind not in self.VALID_KINDS:
            raise ValueError(f"Unsupported handoff kind: {kind}")
        data = asdict(context)
        data["kind"] = kind
        data["created_at"] = datetime.now(timezone.utc).isoformat()
        if kind == "INCIDENT" and not data.get("incident_challenge"):
            data["incident_challenge"] = secrets.token_hex(16)
        return sanitize_mapping(data)  # type: ignore[return-value]

    def build(self, kind: str, context: HandoffContext) -> Path:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        data = self._context(kind, context)
        run_fragment = context.run_id or "NO-RUN"
        name = f"XP_GPT_{kind}_{context.project_id}_{run_fragment}.zip"
        target = self.output_dir / name
        read_first = f"""# Expert Workstation (XP) GPT Handoff\n\nThis package was generated by Expert Workstation (XP).\n\n## Roles\n\n- Human: goals, business decisions, QA, approval, Final Lock.\n- GPT: architecture, audit, coding, and XP-compatible remediation/work packages.\n- XP: workflow authority, execution, verification, recovery, and evidence.\n\n## Current context\n\nProject: {context.project_name} (`{context.project_id}`)\nStage: {context.stage}\nMilestone: {context.milestone or '-'}\nRun: {context.run_id or '-'}\nHandoff kind: {kind}\n\nRead `PROJECT_CONTEXT.json` before proposing actions. Do not bypass XP workflow or ask the human to manually edit project files unless XP cannot represent the required safe action.\n"""
        instructions = """# GPT Instructions\n\n1. Treat XP state/evidence as operational authority.\n2. Evidence before assertion.\n3. Do not expose or request secrets if not necessary.\n4. Return changes as an XP-compatible declarative package when implementation is required.\n5. For incident remediation, preserve run/incident/challenge bindings.\n6. Do not merge main or deploy production automatically.\n"""
        technical = json.dumps(sanitize_mapping(context.technical), indent=2, sort_keys=True)
        context_json = json.dumps(data, indent=2, sort_keys=True)
        with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("00_READ_FIRST.md", redact_text(read_first))
            zf.writestr("GPT_INSTRUCTIONS.md", instructions)
            zf.writestr("PROJECT_CONTEXT.json", context_json)
            zf.writestr("TECHNICAL_STATE.json", technical)
            if context.notes:
                zf.writestr("NOTES.txt", redact_text(context.notes))
        return target
